CREATE DATABASE IF NOT EXISTS NewMdvr2;

USE NewMdvr2;

DROP TABLE  IF EXISTS `t_user`;
CREATE TABLE `t_user`(
`userId` INT(11) NOT NULL AUTO_INCREMENT,
`userType` INT(2) NOT NULL COMMENT '0:系统默认超级用户, 1: ',
`userState` INT(2) NOT NULL COMMENT '0:正常，1：暂停，2：禁用',
`userName` VARCHAR(255) NOT NULL,
`password` VARCHAR(255) NOT NULL,
`createTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`lastLogin` TIMESTAMP NOT NULL DEFAULT 19700101080001,
PRIMARY KEY(`userId`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;